<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIT29JXA\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIT29JXA/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIT29JXA.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIT29JXA\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIT29JXA\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IT29JXA',
    'container.build_id' => '3d1d4e65',
    'container.build_time' => 1610983415,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIT29JXA');
