<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX53LFme\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX53LFme/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX53LFme.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX53LFme\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX53LFme\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X53LFme',
    'container.build_id' => '1b34e3d6',
    'container.build_time' => 1610974665,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX53LFme');
